name    'huit-ilmt'
version '0.3.2'
source 'https://github.com/huit/puppet-ilmt.git'
author 'huit'
license 'MIT License'
summary 'Deploy the IBM License Metric Tool'
description 'Deploys the IBM License Metric Tool.  Currently supports RHEL.'
project_page 'https://github.com/huit/puppet-ilmt'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
